### ISSUE TITLE
Peer dependency for react-metismenu

### ISSUE THREAD

**Issue by cryptk** [alpertuna/react-metismenu-router-link#2]
The latest version of react-metismenu is 1.2.2, but the peerDependency in react-metismenu-router-link is for ~1.1, so we cannot use the router-link plugin with metismenu 1.2 without some modifications.

Also, it would be pretty nice to get a new version pushed up to NPM with the updated package.json with the updated react-router peerDependency (as well as the react-metismenu peerDependency)

**Comment by alpertuna** [comment]
It is updated now and published to npm repos. (`v1.0.1`)
Thanks for your report.
