### ISSUE TITLE
Looks like lib/RouterLink.s is outdated

### ISSUE THREAD

**Issue by flyonme** [alpertuna/react-metismenu-router-link#7]
It doesn't work with React Router v4.

Versions:
├─┬ react-metismenu@1.3.1 
│ └── react-redux@4.4.8 
└── react-metismenu-router-link@2.0.0 

Error:
this.context.router.isActive is not a function

**Comment by alpertuna** [comment]
Hi @isoloviev,
You are right. Actually, it was updated but built files were missed. Now I have published `v2.0.1` with built files.
And, thanks for the report.

**Comment by flyonme** [comment]
Thanks!
